services:
  webapp-frontend:
    image: "zcohn93/webapp-frontend:0.1"
    container_name: webapp-frontend
    ports:
      - 5173:5173
    tty: true
    stdin_open: true

  redis:
    image: "redis:latest"
    container_name: "redis"
    command: ["/bin/sh", "-c", "redis-server --requirepass $$REDIS_PW", "--save", "10", "1", "--loglevel", "warning"]
    volumes:
      - ~/redis/webapp/data:/data
    ports:
      - 6379:6379
    env_file:
      - ${PWD}/secrets/redis_env
